### ISSUE TITLE
Jackett Search broken on Mobile App DSget

### ISSUE THREAD

**Issue by lamplis** [dimitrov-adrian/jackett.dlm#2]
Hi,
On DS get iPhone app, the search is brocken.
I've locally fixed it but i'd like to share the fix.
The DSGET app is broken as soon as it encounters 2 identical Hash.

So I replaced in search.php line 101:
`$hash = '';`
by
`$hash = $count;`

to have unique hash

regards

**Comment by dimitrov-adrian** [comment]
Thanks for the feedback @lamplis

**Comment by lamplis** [comment]
Great job dimitrov!
Thank you for your contribution, your synology search plugin works perfectly on desktop and mobile!
