### ISSUE TITLE
2x every torrent

### ISSUE THREAD

**Issue by Yanom1212** [dimitrov-adrian/jackett.dlm#4]
that show me 2x every torrent from the same tracker when i make a search (exemple 1917) :
1917.2019.2160P.TWN.UHD.BLU-RAY.HEVC.TRUEHD.7.1-NLIBRA (YGGTORRENT)
1917.2019.2160P.TWN.UHD.BLU-RAY.HEVC.TRUEHD.7.1-NLIBRA (YGGTORRENT)
1917.2019.MULTI.2160P.BLURAY.REMUX.HEVC.TRUEHD.7.1.ATMOS-BLACKANGEL (YGGTORRENT)
1917.2019.MULTI.2160P.BLURAY.REMUX.HEVC.TRUEHD.7.1.ATMOS-BLACKANGEL (YGGTORRENT)

**Comment by dimitrov-adrian** [comment]
Can you try direct search in jackett, in my tests, I don't have such issue. But I have only two indexers.

**Comment by Yanom1212** [comment]
ok i found the problem, its a bug with yggtorrent
but that work with Generation-Free, Sharewood , Oasis , Lesaloon

**Comment by dimitrov-adrian** [comment]
Thanks for the feedback!
